#ifndef ZEAL_CONFIG_H_HEADER_GUARD
#define ZEAL_CONFIG_H_HEADER_GUARD

#include "core/platform.h"

#define ZEAL_VERSION "0.1.0"

#ifndef ZEAL_DEFAULT_WINDOW_WIDTH
#define ZEAL_DEFAULT_WINDOW_WIDTH 1280
#endif // ZEAL_DEFAULT_WINDOW_WIDTH

#ifndef ZEAL_DEFAULT_WINDOW_HEIGHT
#define ZEAL_DEFAULT_WINDOW_HEIGHT 720
#endif // ZEAL_DEFAULT_WINDOW_HEIGHT

#ifndef ZEAL_DEFAULT_CONSOLE_PORT
#define ZEAL_DEFAULT_CONSOLE_PORT 10001
#endif // ZEAL_DEFAULT_CONSOLE_PORT

#endif // ZEAL_CONFIG_H_HEADER_GUARD