#ifndef ZEAL_CONFIG_H_HEADER_GUARD
#define ZEAL_CONFIG_H_HEADER_GUARD

#include "core/platform.h"

#define ZEAL_VERSION "0.1.0"

#ifndef ZEAL_DEFAULT_WINDOW_WIDTH
#define ZEAL_DEFAULT_WINDOW_WIDTH 1280
#endif // ZEAL_DEFAULT_WINDOW_WIDTH

#ifndef ZEAL_DEFAULT_WINDOW_HEIGHT
#define ZEAL_DEFAULT_WINDOW_HEIGHT 720
#endif // ZEAL_DEFAULT_WINDOW_HEIGHT

#ifndef ZEAL_DEFAULT_CONSOLE_PORT
#define ZEAL_DEFAULT_CONSOLE_PORT 10001
#endif // ZEAL_DEFAULT_CONSOLE_PORT

#ifndef ZEAL_DEFAULT_COMPILER_PORT
#define ZEAL_DEFAULT_COMPILER_PORT 10618
#endif // ZEAL_DEFAULT_COMPILER_PORT

#ifndef ZEAL_DATA_DIRECTORY
#define ZEAL_DATA_DIRECTORY "data"
#endif // ZEAL_DATA_DIRECTORY

#ifndef ZEAL_TEMP_DIRECTORY
#define ZEAL_TEMP_DIRECTORY "temp"
#endif // ZEAL_TEMP_DIRECTORY

#ifndef ZEAL_DATAIGNORE
#define ZEAL_DATAIGNORE ".dataignore"
#endif // ZEAL_DATAIGNORE

#ifndef ZEAL_LUA_MAX_VECTOR3_SIZE
#define ZEAL_LUA_MAX_VECTOR3_SIZE (129 * 1024)
#endif // ZE_MAX

#ifndef ZEAL_LUA_MAX_QUATERNION_SIZE
#define ZEAL_LUA_MAX_QUATERNION_SIZE (128 * 1024)
#endif // ZE_MAX

#ifndef ZEAL_LUA_MAX_MATRIX4X4_SIZE
#define ZEAL_LUA_MAX_MATRIX4X4_SIZE (128 * 1024)
#endif // ZE_MAX

#endif // ZEAL_CONFIG_H_HEADER_GUARD